#声明电影购票微服务的端口号
server:
  port: 8001

spring:
  application:
    name: microservice-movie

#eureka客户端向eureka服务器注册
eureka:
  client:
    #向Eure服务器注册
    register-with-eureka: true
    #向eureka服务器索要信息
    fetch-registry: true
    #注册服务的url
    service-url:
      defaultZone: http://192.168.203.1:8888/eureka

    #微服务的消费方与eureka服务器的约定
    #每30秒从eureka服务器获得最新的信息
    registry-fetch-interval-seconds: 30 #默认30秒